version: '2'

services:
  rails:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./script/run-local
    ports:
      - '3000:3000'
    networks:
      - private
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      RACK_ENV: development
      RAILS_ENV: development

networks:
  private:
    driver: bridge
